version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: adt62497
      POSTGRES_USER: aaron
      POSTGRES_DB: ttp
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  web:
    image: ttp-fs
    depends_on: 
      - db
    ports:
      - "3000:3000" 